; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examcdples
; https://docs.platformio.org/page/projectconf.html

; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino

; monitor_speed = 115200 dữ l
; monitor_filters = esp32_exception_decoder

; lib_deps =
;     knolleary/PubSubClient
;     bblanchon/ArduinoJson@6.21.3
;     Wire

; build_flags =
;     -DCORE_DEBUG_LEVEL=0
[env:esp32dev]
platform = espressif32
board = esp32dev 
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
  knolleary/PubSubClient
  bblanchon/ArduinoJson
  adafruit/Adafruit MPU6050
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit BusIO
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  adafruit/Adafruit SH110X

build_flags =
  -DOLED_ENABLED=1
  -DOLED_DRIVER=1
  -DOLED_SDA=26
  -DOLED_SCL=27
  -DOLED_ADDR=0x3C
  -DOLED_ADDR_FALLBACK=0x3D
