// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJu4Ok18qxGDSneoIOcf16yK3CamgDRkM',
    appId: '1:318222962298:web:26d8152febe9d27cb975c3',
    messagingSenderId: '318222962298',
    projectId: 'drowsy-monitor',
    authDomain: 'drowsy-monitor.firebaseapp.com',
    storageBucket: 'drowsy-monitor.firebasestorage.app',
    measurementId: 'G-5165E7X4WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxR9clfQPkIwIdUnrOE5L7OndNqU6ciA8',
    appId: '1:318222962298:android:5fa57b4e692ce446b975c3',
    messagingSenderId: '318222962298',
    projectId: 'drowsy-monitor',
    storageBucket: 'drowsy-monitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3upQ7-Fx_VW3n2bPhyu7r63dIb0a8x0o',
    appId: '1:318222962298:ios:67be6ed44b381eddb975c3',
    messagingSenderId: '318222962298',
    projectId: 'drowsy-monitor',
    storageBucket: 'drowsy-monitor.firebasestorage.app',
    iosBundleId: 'com.example.sleepyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3upQ7-Fx_VW3n2bPhyu7r63dIb0a8x0o',
    appId: '1:318222962298:ios:67be6ed44b381eddb975c3',
    messagingSenderId: '318222962298',
    projectId: 'drowsy-monitor',
    storageBucket: 'drowsy-monitor.firebasestorage.app',
    iosBundleId: 'com.example.sleepyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJu4Ok18qxGDSneoIOcf16yK3CamgDRkM',
    appId: '1:318222962298:web:c0f877f18d7f445cb975c3',
    messagingSenderId: '318222962298',
    projectId: 'drowsy-monitor',
    authDomain: 'drowsy-monitor.firebaseapp.com',
    storageBucket: 'drowsy-monitor.firebasestorage.app',
    measurementId: 'G-VK3W5WGC19',
  );
}
